### ISSUE TITLE
一运行就报错

### ISSUE THREAD

**Issue by dfaofeng** [reycn/fanyi_bot#1]
fanyi_bot架设在tx云上,,,好像连不上
![QQ截图20200313212651](https://user-images.githubusercontent.com/14891398/76625215-b7591580-6571-11ea-97be-f19458af8260.png)
报错信息

**Comment by reycn** [comment]
> fanyi_bot架设在tx云上,,,好像连不上
> ![QQ截图20200313212651](https://user-images.githubusercontent.com/14891398/76625215-b7591580-6571-11ea-97be-f19458af8260.png)
> 报错信息

Telgram api 需要国外的服务器的顺畅访问，你可以再试试 ：）。
